package it.zeze.fantaformazioneweb.entity;

// Generated 19-gen-2012 10.57.55 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CalendarioId generated by hbm2java
 */
@Embeddable
public class CalendarioId implements java.io.Serializable {

	private int idGiornata;
	private int idSquadraCasa;
	private int idSquadraFuoriCasa;

	public CalendarioId() {
	}

	public CalendarioId(int idGiornata, int idSquadraCasa, int idSquadraFuoriCasa) {
		this.idGiornata = idGiornata;
		this.idSquadraCasa = idSquadraCasa;
		this.idSquadraFuoriCasa = idSquadraFuoriCasa;
	}

	@Column(name = "id_giornata", nullable = false)
	public int getIdGiornata() {
		return this.idGiornata;
	}

	public void setIdGiornata(int idGiornata) {
		this.idGiornata = idGiornata;
	}

	@Column(name = "id_squadra_casa", nullable = false)
	public int getIdSquadraCasa() {
		return this.idSquadraCasa;
	}

	public void setIdSquadraCasa(int idSquadraCasa) {
		this.idSquadraCasa = idSquadraCasa;
	}

	@Column(name = "id_squadra_fuori_casa", nullable = false)
	public int getIdSquadraFuoriCasa() {
		return this.idSquadraFuoriCasa;
	}

	public void setIdSquadraFuoriCasa(int idSquadraFuoriCasa) {
		this.idSquadraFuoriCasa = idSquadraFuoriCasa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CalendarioId))
			return false;
		CalendarioId castOther = (CalendarioId) other;

		return (this.getIdGiornata() == castOther.getIdGiornata()) && (this.getIdSquadraCasa() == castOther.getIdSquadraCasa()) && (this.getIdSquadraFuoriCasa() == castOther.getIdSquadraFuoriCasa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdGiornata();
		result = 37 * result + this.getIdSquadraCasa();
		result = 37 * result + this.getIdSquadraFuoriCasa();
		return result;
	}

}
