package it.zeze.fantaformazioneweb.entity;

// Generated 19-gen-2012 10.57.55 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FormazioniId generated by hbm2java
 */
@Embeddable
public class FormazioniId implements java.io.Serializable {

	private int idGiocatore;
	private int idUtentiFormazioni;

	public FormazioniId() {
	}

	public FormazioniId(int idGiocatore, int idUtentiFormazioni) {
		this.idGiocatore = idGiocatore;
		this.idUtentiFormazioni = idUtentiFormazioni;
	}

	@Column(name = "id_giocatore", nullable = false)
	public int getIdGiocatore() {
		return this.idGiocatore;
	}

	public void setIdGiocatore(int idGiocatore) {
		this.idGiocatore = idGiocatore;
	}

	@Column(name = "id_utenti_formazioni", nullable = false)
	public int getIdUtentiFormazioni() {
		return this.idUtentiFormazioni;
	}

	public void setIdUtentiFormazioni(int idUtentiFormazioni) {
		this.idUtentiFormazioni = idUtentiFormazioni;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FormazioniId))
			return false;
		FormazioniId castOther = (FormazioniId) other;

		return (this.getIdGiocatore() == castOther.getIdGiocatore()) && (this.getIdUtentiFormazioni() == castOther.getIdUtentiFormazioni());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdGiocatore();
		result = 37 * result + this.getIdUtentiFormazioni();
		return result;
	}

}
