package it.zeze.fantaformazioneweb.entity;

// Generated 19-gen-2012 10.57.55 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Giornate generated by hbm2java
 */
@Entity
@Table(name = "giornate", catalog = "fanta_formazione")
public class Giornate implements java.io.Serializable {

	private Integer id;
	private Integer numeroGiornata;
	private String stagione;
	private Date data;
	private Set<Statistiche> statistiches = new HashSet<Statistiche>(0);
	private Set<ProbabiliFormazioniFg> probabiliFormazioniFgs = new HashSet<ProbabiliFormazioniFg>(0);
	private Set<ProbabiliFormazioniGazzetta> probabiliFormazioniGazzettas = new HashSet<ProbabiliFormazioniGazzetta>(0);
	private Set<Calendario> calendarios = new HashSet<Calendario>(0);
	private Set<ProbabiliFormazioni> probabiliFormazionis = new HashSet<ProbabiliFormazioni>(0);

	public Giornate() {
	}

	public Giornate(Date data, Set<Statistiche> statistiches, Set<ProbabiliFormazioniFg> probabiliFormazioniFgs, Set<ProbabiliFormazioniGazzetta> probabiliFormazioniGazzettas, Set<Calendario> calendarios, Set<ProbabiliFormazioni> probabiliFormazionis) {
		this.data = data;
		this.statistiches = statistiches;
		this.probabiliFormazioniFgs = probabiliFormazioniFgs;
		this.probabiliFormazioniGazzettas = probabiliFormazioniGazzettas;
		this.calendarios = calendarios;
		this.probabiliFormazionis = probabiliFormazionis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "numero_giornata", nullable = false)
	@NotNull
	public Integer getNumeroGiornata() {
		return numeroGiornata;
	}

	public void setNumeroGiornata(Integer numeroGiornata) {
		this.numeroGiornata = numeroGiornata;
	}

	@Column(name = "stagione", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getStagione() {
		return this.stagione;
	}

	public void setStagione(String stagione) {
		this.stagione = stagione;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giornate")
	public Set<Statistiche> getStatistiches() {
		return this.statistiches;
	}

	public void setStatistiches(Set<Statistiche> statistiches) {
		this.statistiches = statistiches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giornate")
	public Set<ProbabiliFormazioniFg> getProbabiliFormazioniFgs() {
		return this.probabiliFormazioniFgs;
	}

	public void setProbabiliFormazioniFgs(Set<ProbabiliFormazioniFg> probabiliFormazioniFgs) {
		this.probabiliFormazioniFgs = probabiliFormazioniFgs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giornate")
	public Set<ProbabiliFormazioniGazzetta> getProbabiliFormazioniGazzettas() {
		return this.probabiliFormazioniGazzettas;
	}

	public void setProbabiliFormazioniGazzettas(Set<ProbabiliFormazioniGazzetta> probabiliFormazioniGazzettas) {
		this.probabiliFormazioniGazzettas = probabiliFormazioniGazzettas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giornate")
	public Set<Calendario> getCalendarios() {
		return this.calendarios;
	}

	public void setCalendarios(Set<Calendario> calendarios) {
		this.calendarios = calendarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giornate")
	public Set<ProbabiliFormazioni> getProbabiliFormazionis() {
		return this.probabiliFormazionis;
	}

	public void setProbabiliFormazionis(Set<ProbabiliFormazioni> probabiliFormazionis) {
		this.probabiliFormazionis = probabiliFormazionis;
	}

}
