package it.zeze.fantaformazioneweb.entity;

// Generated 19-gen-2012 10.57.55 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * ProbabiliFormazioni generated by hbm2java
 */
@Entity
@Table(name = "probabili_formazioni", catalog = "fanta_formazione")
public class ProbabiliFormazioni implements java.io.Serializable {

	private ProbabiliFormazioniId id;
	private Giornate giornate;
	private UtentiFormazioni utentiFormazioni;
	private Giocatori giocatori;

	public ProbabiliFormazioni() {
	}

	public ProbabiliFormazioni(ProbabiliFormazioniId id, Giornate giornate, UtentiFormazioni utentiFormazioni, Giocatori giocatori) {
		this.id = id;
		this.giornate = giornate;
		this.utentiFormazioni = utentiFormazioni;
		this.giocatori = giocatori;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idGiornate", column = @Column(name = "id_giornate", nullable = false)), @AttributeOverride(name = "idUtentiFormazioni", column = @Column(name = "id_utenti_formazioni", nullable = false)), @AttributeOverride(name = "idGiocatore", column = @Column(name = "id_giocatore", nullable = false)), @AttributeOverride(name = "probTitolare", column = @Column(name = "prob_titolare", nullable = false)), @AttributeOverride(name = "probPanchina", column = @Column(name = "prob_panchina", nullable = false)), @AttributeOverride(name = "note", column = @Column(name = "note", length = 100)) })
	@NotNull
	public ProbabiliFormazioniId getId() {
		return this.id;
	}

	public void setId(ProbabiliFormazioniId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giornate", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Giornate getGiornate() {
		return this.giornate;
	}

	public void setGiornate(Giornate giornate) {
		this.giornate = giornate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_utenti_formazioni", nullable = false, insertable = false, updatable = false)
	@NotNull
	public UtentiFormazioni getUtentiFormazioni() {
		return this.utentiFormazioni;
	}

	public void setUtentiFormazioni(UtentiFormazioni utentiFormazioni) {
		this.utentiFormazioni = utentiFormazioni;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giocatore", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Giocatori getGiocatori() {
		return this.giocatori;
	}

	public void setGiocatori(Giocatori giocatori) {
		this.giocatori = giocatori;
	}

}
