package it.zeze.fantaformazioneweb.entity;

// Generated 19-gen-2012 10.57.55 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ProbabiliFormazioniGazzetta generated by hbm2java
 */
@Entity
@Table(name = "probabili_formazioni_gazzetta", catalog = "fanta_formazione")
public class ProbabiliFormazioniGazzetta implements java.io.Serializable {

	private ProbabiliFormazioniGazzettaId id;
	private Giocatori giocatori;
	private Giornate giornate;

	public ProbabiliFormazioniGazzetta() {
	}

	public ProbabiliFormazioniGazzetta(ProbabiliFormazioniGazzettaId id, Giocatori giocatori, Giornate giornate) {
		this.id = id;
		this.giocatori = giocatori;
		this.giornate = giornate;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "idGiocatore", column = @Column(name = "id_giocatore", nullable = false)), @AttributeOverride(name = "idGiornata", column = @Column(name = "id_giornata", nullable = false)), @AttributeOverride(name = "titolare", column = @Column(name = "titolare")), @AttributeOverride(name = "panchina", column = @Column(name = "panchina")) })
	@NotNull
	public ProbabiliFormazioniGazzettaId getId() {
		return this.id;
	}

	public void setId(ProbabiliFormazioniGazzettaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giocatore", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Giocatori getGiocatori() {
		return this.giocatori;
	}

	public void setGiocatori(Giocatori giocatori) {
		this.giocatori = giocatori;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giornata", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Giornate getGiornate() {
		return this.giornate;
	}

	public void setGiornate(Giornate giornate) {
		this.giornate = giornate;
	}

}
