package it.zeze.fantaformazioneweb.entity;

// Generated 19-gen-2012 10.57.55 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * UtentiFormazioni generated by hbm2java
 */
@Entity
@Table(name = "utenti_formazioni", catalog = "fanta_formazione")
public class UtentiFormazioni implements java.io.Serializable {

	private Integer id;
	private Utenti utenti;
	private String nomeFormazione;
	private BigDecimal crediti;
	private Set<ProbabiliFormazioni> probabiliFormazionis = new HashSet<ProbabiliFormazioni>(0);
	private Set<Formazioni> formazionis = new HashSet<Formazioni>(0);

	public UtentiFormazioni() {
	}

	public UtentiFormazioni(Utenti utenti, String nomeFormazione) {
		this.utenti = utenti;
		this.nomeFormazione = nomeFormazione;
	}

	public UtentiFormazioni(Utenti utenti, String nomeFormazione, Set<ProbabiliFormazioni> probabiliFormazionis, Set<Formazioni> formazionis) {
		this.utenti = utenti;
		this.nomeFormazione = nomeFormazione;
		this.probabiliFormazionis = probabiliFormazionis;
		this.formazionis = formazionis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_utente", nullable = false)
	@NotNull
	public Utenti getUtenti() {
		return this.utenti;
	}

	public void setUtenti(Utenti utenti) {
		this.utenti = utenti;
	}

	@Column(name = "nome_formazione", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getNomeFormazione() {
		return this.nomeFormazione;
	}

	public void setNomeFormazione(String nomeFormazione) {
		this.nomeFormazione = nomeFormazione;
	}

	@Column(name = "crediti", nullable = true, precision = 4, scale = 2)
	public BigDecimal getCrediti() {
		return crediti;
	}

	public void setCrediti(BigDecimal crediti) {
		this.crediti = crediti;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utentiFormazioni")
	public Set<ProbabiliFormazioni> getProbabiliFormazionis() {
		return this.probabiliFormazionis;
	}

	public void setProbabiliFormazionis(Set<ProbabiliFormazioni> probabiliFormazionis) {
		this.probabiliFormazionis = probabiliFormazionis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utentiFormazioni")
	public Set<Formazioni> getFormazionis() {
		return this.formazionis;
	}

	public void setFormazionis(Set<Formazioni> formazionis) {
		this.formazionis = formazionis;
	}

}
